<div class="container theme-showcase" role="main">

	<div class="panel panel-primary">
	    <div class="panel-heading">
	       <small>Pencarian</small>
	    </div>
	    <div class="panel-body">
	            <table class="table">
	                <tbody>
	                	<tr>
	                        <td width="20%"><small>Tahun</small></td>
	                        <td width="1%"><small>:</small></td>
	                        <td width="79%"><small>
	                              <select class="form-control chzn-selectform" id="tahunsearch" <?php echo @$this->disabled; ?>>
	                                 <option value="">[ - Pilih Tahun - ]</option>
	                                 <?php
	                                 
	                                  foreach($this->tahuns as $id => $nilai){
	                                          echo "<option value='".$id."'>".$nilai."</option>";
	                                  }
	                                  ?>
	                              </select>
	                              
	                        </td>
	                    </tr>
	                    <tr>
	                        <td width="20%"><small>BUMN</small></td>
	                        <td width="1%"><small>:</small></td>
	                        <td width="79%"><small>
	                              <select class="form-control chzn-selectform" id="bumnsearch" <?php echo @$this->disabled; ?>>
	                                 <?php
	                                 if(@$this->cntcombobumn > 1){
	                                 ?>
	                                    <option value="">[ - Pilih BUMN - ]</option>
	                                 <?php
	                                 }
	                                  foreach($this->combobumn2 as $key => $value){
	                                          echo "<option value='".$value['bumn_id']."'>".$value['bumn_nama']."</option>";
	                                  }
	                                  ?>
	                              </select>
	                              
	                        </td>
	                    </tr>
	                    <tr>
	                        <td width="20%"><small>Periode</small></td>
	                        <td width="1%"><small>:</small></td>
	                        <td width="79%"><small>
	                              <select class="form-control chzn-selectform" id="periodesearch" <?php echo @$this->disabled; ?>>
	                              <?php
	                                 if(@$this->cntperiode > 1){
	                              ?>
	                              <option value="">[ - Pilih Periode - ]</option>
	                                 <?php
	                                 }
	                                  foreach($this->comboperiodes as $key => $value){
	                                          echo "<option value='".$value['id']."'>".$value['nama']."</option>";
	                                  }
	                                  ?>
	                              </select>
	                              
	                        </td>
	                    </tr>                  
	                    
	                </tbody>
	            </table>
	    </div>
	</div>
	
	<div class="panel panel-primary">
	    <div class="panel-heading">
	        <i class="mdi-content-content-paste"></i>
	    </div>
	    <div class="panel-body table-responsive">
	           
	        <div id="messageproyeksinergi"></div>
<!-- 
	        <?
	        if(@$this->groupinduk == 20000 || @$this->groupinduk == 1){
	        ?>       
 -->
	        <button data-target="#modaladdlkpn" data-toggle="modal" class="btn btn-primary"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Tambah Data</button>

	        <!--<? } ?>-->
	        <button class="btn btn-primary" type="button" onclick="location.href='/laporan/viewinput/lanjut/1'">Hide</button>
	           
	        <div id="wrapper2">
	          <div id="div2">
	            &nbsp;	
	          </div>
	        </div>
	        <div id="wrapper3" class="da-panel-content">    
	        <table class="table table-striped table-hover table-bordered" id="tablelkpn">
	          <thead>
	            <tr>
	              <th></th>
	            	<th><small>BUMN</small></th>
	            	<th><small>Periode</small></th>
	            	<th><small>Tahun</small></th>
	            	<th><small>% Saham Pemerintah</small></th>
	            	<th><small>Total Aset</small></th>
	            	<th><small>Total Liabilitas</small></th>
	            	<th><small>Total Ekuitas</small></th>
	            	<th><small>Pendapatan Usaha</small></th>
	            	<th><small>Laba Tahun Berjalan</small></th>
	            	<th><small>Laba Tahun Berjalan Diatribusikan Entitas Pengendali</small></th>
	            	<th><small>Belanja Modal</small></th>
	            	<th><small>Setoran Pajak</small></th>
	            	<th><small>Setoran Dividen</small></th>
	            	<th><small>EBITDA</small></th>
	            	<th><small>Arus Kas Koperasi</small></th>
	              <th><div align="center"><small>Aksi</small></div></th>
	            </tr>
	          </thead>
	          <tbody>
	          </tbody>
	        </table>
	        </div>
	        
	    </div>
	</div>
</div>


<div class="modal fade" id="modaladdlkpn" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Pengisian Data LKPN</h4>
        <div id="notifikasi">(*PERHATIAN untuk koma menggunakan titik di isian angka)</div>
      </div>
      <div class="modal-body">
        <fieldset style="width: 100%;" class="panel">
        	<div class="panel panel-primary">
            
            <div class="panel-body">
              <form method="post" id="simpanlkpn" name="simpanlkpn" >

              	  <div class="form-group">
				    <label >Tahun</label>
				    
				    <select class="form-control" name="tahunbumn">
	                     <option value="">[ - Pilih Tahun - ]</option>
	                     <?php
	                     
	                      foreach($this->tahuns as $id => $nilai){
	                              echo "<option value='".$id."'>".$nilai."</option>";
	                      }
	                      ?>
	                  </select>
				  </div>

				  <div class="form-group">
				    <label >BUMN</label>
				    
				    <select class="form-control" name="lkpnbumn" <?php echo @$this->disabled; ?>>
                         <?php
                         if(@$this->cntcombobumn > 1){
                         ?>
                            <option value="">[ - Pilih BUMN - ]</option>
                         <?php
                         }
                          foreach($this->combobumn2 as $key => $value){
                                  echo "<option value='".$value['bumn_id']."'>".$value['bumn_nama']."</option>";
                          }
                          ?>
                      </select>
				  </div>
				  
				  <div class="form-group">
				    <label >Periode</label>
				    
				    <select class="form-control" name="periodebumn" <?php echo @$this->disabled; ?>>
				    	<?php
				    	if(@$this->cntperiode > 1){
				    		?>
				    		<option value="">[ - Pilih Periode - ]</option>
				    		<?php
				    	}
				    	foreach($this->comboperiodes as $key => $value){
				    		echo "<option value='".$value['id']."'>".$value['nama']."</option>";
				    	}
				    	?>
	                </select>
				  </div>

				  <div class="form-group">
				    <label >% Saham Pemerintah</label>
				    
				    <input class="form-control" placeholder="Saham Pemerintah" id="saham" size="5" name="saham" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Total Aset</label>
				    
				    <input class="form-control" placeholder="Total Aset" id="aset" name="aset" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Total Liabilitas</label>
				    
				    <input class="form-control" placeholder="Total Liabilitas" id="liabilitas" name="liabilitas" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Total Ekuitas</label>
				    
				    <input class="form-control" placeholder="Total Ekuitas" id="ekuitas" name="ekuitas" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Pendapatan Usaha</label>
				    
				    <input class="form-control" placeholder="Pendapatan Usaha" id="pend_usaha" name="pend_usaha" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Laba Tahun Berjalan</label>
				    
				    <input class="form-control" placeholder="Laba Tahun Berjalan" id="laba" name="laba" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Laba Tahun Berjalan Atribusi</label>
				    
				    <input class="form-control" placeholder="Laba Tahun Berjalan Atribusi" id="laba_atribusi" name="laba_atribusi" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Belanja Modal</label>
				    
				    <input class="form-control" placeholder="Belanja Modal" id="modal" name="modal" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >SDM</label>
				    
				    <input class="form-control" placeholder="SDM" id="sdm" name="sdm" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Setoran Pajak</label>
				    
				    <input class="form-control" placeholder="Setoran Pajak" id="pajak" name="pajak" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Setoran Dividen</label>
				    
				    <input class="form-control" placeholder="Setoran Dividen" id="dividen" name="dividen" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >EBITDA</label>
				    
				    <input class="form-control" placeholder="EBITDA" id="ebitda" name="ebitda" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Arus Kas Operasi</label>
				    
				    <input class="form-control" placeholder="Arus Kas Koperasi" id="kas_operasi" name="kas_operasi" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  
				  <button type="submit" name="lanjut" value="Lanjut" class="btn btn-primary">Simpan</button>
				  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</form>
            </div>
          </div>
      </fieldset>
  </div>
  </div>
  </div>
</div>

<div class="modal fade" id="modalbatalkpku" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Pesan Invalid Data KPKU</h4>
        <div id="notifikasi"></div>
      </div>
      <div class="modal-body">
        <fieldset style="width: 100%;" class="panel">
        	<div class="panel panel-primary">
            
            <div class="panel-body">
              <form method="post" id="simpaninvalidkpku" name="simpaninvalidkpku" >

              	  
				  
				  <div class="form-group">
				    <label >Pesan</label>
				    
				    <textarea class="form-control" rows="3" name="invalidkpku"></textarea>
				    <input type="hidden" name="bumnkpkuid" id="bumnkpkuid">
				  </div>
				  
				   
				  
				  <button type="submit" name="lanjut" value="Lanjut" class="btn btn-primary">Simpan</button>
				  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</form>
            </div>
          </div>
      </fieldset>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="modaleditlkpn" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Edit Pengisian Data LKPN</h4>
        <div id="notifikasi">(*PERHATIAN untuk koma menggunakan titik di isian angka)</div>
      </div>
      <div class="modal-body">
        <fieldset style="width: 100%;" class="panel">
        	<div class="panel panel-primary">
            
            <div class="panel-body">
              <form method="post" id="simpaneditlkpn" name="simpaneditlkpn" >
              	  <input type="hidden" name="editlkpnid" id="editlkpnid">

              	  <div class="form-group">
				    <label >Tahun</label>
				    
				    <select class="form-control" name="tahunbumn" id="edittahunbumn">
	                     <option value="">[ - Pilih Tahun - ]</option>
	                     <?php
	                     
	                      foreach($this->tahuns as $id => $nilai){
	                              echo "<option value='".$id."'>".$nilai."</option>";
	                      }
	                      ?>
	                  </select>
				  </div>

				  <div class="form-group">
				    <label >BUMN</label>
				    
				    <select class="form-control" name="lkpnbumn" <?php echo @$this->disabled; ?> id="editlkpnbumn">
                         <?php
                         if(@$this->cntcombobumn > 1){
                         ?>
                            <option value="">[ - Pilih BUMN - ]</option>
                         <?php
                         }
                          foreach($this->combobumn2 as $key => $value){
                                  echo "<option value='".$value['bumn_id']."'>".$value['bumn_nama']."</option>";
                          }
                          ?>
                      </select>
				  </div>

				  <div class="form-group">
				    <label >Periode</label>
				    
				    <select class="form-control" name="periodebumn" <?php echo @$this->disabled; ?> id="editperiodebumn">
				    	<?php
				    	if(@$this->cntperiode > 1){
				    		?>
				    		<option value="">[ - Pilih Periode - ]</option>
				    		<?php
				    	}
				    	foreach($this->comboperiodes as $key => $value){
				    		echo "<option value='".$value['id']."'>".$value['nama']."</option>";
				    	}
				    	?>
	                </select>
				  </div>

				  <div class="form-group">
				    <label >% Saham Pemerintah</label>
				    
				    <input class="form-control" placeholder="Saham Pemerintah" id="editsaham" size="5" name="saham" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Total Aset</label>
				    
				    <input class="form-control" placeholder="Total Aset" id="editaset" name="aset" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Total Liabilitas</label>
				    
				    <input class="form-control" placeholder="Total Liabilitas" id="editliabilitas" name="liabilitas" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Total Ekuitas</label>
				    
				    <input class="form-control" placeholder="Total Ekuitas" id="editekuitas" name="ekuitas" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Pendapatan Usaha</label>
				    
				    <input class="form-control" placeholder="Pendapatan Usaha" id="editpend_usaha" name="pend_usaha" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Laba Tahun Berjalan</label>
				    
				    <input class="form-control" placeholder="Laba Tahun Berjalan" id="editlaba" name="laba" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Laba Tahun Berjalan Atribusi</label>
				    
				    <input class="form-control" placeholder="Laba Tahun Berjalan Atribusi" id="editlaba_atribusi" name="laba_atribusi" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Belanja Modal</label>
				    
				    <input class="form-control" placeholder="Belanja Modal" id="editmodal" name="modal" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >SDM</label>
				    
				    <input class="form-control" placeholder="SDM" id="editsdm" name="sdm" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Setoran Pajak</label>
				    
				    <input class="form-control" placeholder="Setoran Pajak" id="editpajak" name="pajak" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Setoran Dividen</label>
				    
				    <input class="form-control" placeholder="Setoran Dividen" id="editdividen" name="dividen" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >EBITDA</label>
				    
				    <input class="form-control" placeholder="EBITDA" id="editebitda" name="ebitda" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  <div class="form-group">
				    <label >Arus Kas Operasi</label>
				    
				    <input class="form-control" placeholder="Arus Kas Koperasi" id="editkas_operasi" name="kas_operasi" onkeyup="return numericFilter(this), formatNumber(this);">
				  </div>
				  
				   
				  
				  <button type="submit" name="lanjut" value="Lanjut" class="btn btn-primary">Simpan</button>
				  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</form>
            </div>
          </div>
      </fieldset>
      </div>
    </div>
  </div>
</div>